# Database connection settings
spring.datasource.url=jdbc:mysql://localhost:3306/ourexp
spring.datasource.username=ourexp
spring.datasource.password=Feelings123

# Specify the DBMS
spring.jpa.database = MYSQL

# Show log for each sql query?
spring.jpa.show-sql = false

# Hibernate ddl auto (create, create-drop, update)
spring.jpa.hibernate.ddl-auto = update

# Enable OSIV?
spring.jpa.open-in-view = true

# GitHub login
spring.security.oauth2.client.registration.github.client-id = Ov23lirOhUU4yDtPXCjs
spring.security.oauth2.client.registration.github.client-secret = ${GITHUB_CLIENT_SECRET}

# Google login
spring.security.oauth2.client.registration.google.client-id = 579410253327-fca4gl50vqfvrob0op45jlnfis0285p0.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret = ${GOOGLE_CLIENT_SECRET}